### ISSUE TITLE
Make sure all designs for updated profile designs are in line with wireframes

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#740]
This relates to issues from  #729 to #738 

- [x] Update design of 'Log in' page with copy, buttons and colours
In Figma, refer to the page called _Updated Log in_ page.

- [x] Update design of 'Sign up' page with copy, buttons, Tool Tips and colours
In Figma, refer to the page called _Updated Sign up page_.

- [x] Update the design of the entity profile pages (for access levels 1, 2 and 3) with copy, buttons and colours
In Figma, refer to the page called _Updated profile pages_.

- [x] Update the design of the entity review pages with copy, buttons, Tool Tips and colours
In Figma, refer to the page called _Updated review questions_.

- [ ] Update the design of all other pages with copy, buttons, Tool Tips and colours
In Figma, refer to the page called Updated other pages.
