### ISSUE TITLE
Updates to entity profile functionality and designs

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#796]
We must update the functionality and the designs to the entity profiles in the following ways:

**Functionality**
- [ ] Create two new tabs within each profile called 'Overview' and 'Detailed'
- [ ] Ensure a coloured line underlines whichever tab is currently open
- [ ] Add icons (see this folder: https://drive.google.com/open?id=1rtzCm0edRuuJSHWSuHiGWBlohnPEQUGJ)
<img width="323" alt="Screenshot 2019-11-19 at 13 50 49" src="https://user-images.githubusercontent.com/45825100/69152032-a7ee2200-0ad3-11ea-92ed-82de2b3f6a6b.png">
-

- [ ] Render company overall star rating in the coloured header bar
<img width="264" alt="Screenshot 2019-11-20 at 13 39 13" src="https://user-images.githubusercontent.com/45825100/69243524-29f54e00-0b9b-11ea-9c6a-a89b1d1258c6.png">
-

- [ ] Remove buttons (for email, phone and website) and render this information as hyperlinked text
<img width="338" alt="Screenshot 2019-11-20 at 13 33 35" src="https://user-images.githubusercontent.com/45825100/69243163-62e0f300-0b9a-11ea-9073-99f2f2685382.png">
-

- [ ] Render the written/voice reviews in the 'Overview' tab
- [ ] Render the data bars in the 'Detailed' tab
- [ ] When user scrolls, fix only the Overview and Detailed tabs (_not_ the earwig header bar nor the 'Review this entity' button)
<img width="299" alt="Screenshot 2019-11-20 at 14 16 18" src="https://user-images.githubusercontent.com/45825100/69246298-5e1f3d80-0ba0-11ea-98d0-602067a5ed95.png">
-

- [ ] Update 'Helpful' and 'Reply' buttons
- [ ] Make 'Helpful' button fill grey when clicked
<img width="301" alt="Screenshot 2019-11-20 at 14 44 34" src="https://user-images.githubusercontent.com/45825100/69248507-52357a80-0ba4-11ea-95fb-3e384558517f.png">
-

- [ ] Move the review author's username and stats to below their review
<img width="244" alt="Screenshot 2019-11-20 at 14 40 30" src="https://user-images.githubusercontent.com/45825100/69248207-c3286280-0ba3-11ea-8830-59232765e4e2.png">
-

- [ ] Add star ratings from each worker beside their username and stats
<img width="316" alt="Screenshot 2019-11-19 at 13 51 45" src="https://user-images.githubusercontent.com/45825100/69152110-c9e7a480-0ad3-11ea-8e3d-942dc094fa50.png">
-

- [ ] But keep usernames and stats from replies as they are (_above_ their reply)
<img width="391" alt="Screenshot 2019-11-20 at 14 42 46" src="https://user-images.githubusercontent.com/45825100/69248373-18fd0a80-0ba4-11ea-8a47-91e66cd58fe1.png">

**Design**
- [ ] Update overall layout of profile pages
- [ ] Reorder the sequence of data bars in Worksite profile
- [ ] Reorder the sequence of data bars in Company profile

- [ ] Ensure there are faint lines separating each review
<img width="323" alt="Screenshot 2019-11-19 at 14 01 33" src="https://user-images.githubusercontent.com/45825100/69152904-2a2b1600-0ad5-11ea-8976-1e19e4a8a544.png">
-

- [ ] Ensure title fonts are size 18 and **bold**
- [ ] Ensure subtitle fonts are size 15 and **bold**
- [ ] Ensure all other fonts are size 15 and regular
- [ ] Ensure empty profiles designs are updated to reflect new changes

**Level 1 profile pages (when users skip signup)**
- [ ] Don't render 'Overview' and 'Detailed' tabs
- [ ] Don't render contact info section
- [ ] Ensure written/voice reviews are shown first, while the blurred-out data bars are shown after
- [ ] Ensure no more than three reviews can be seen as a level 1 user

Please refer to the page called 'Updated profile pages' in the wireframes.
Ensure consistency across both mobile and desktop.

**Comment by thejoefriel** [comment]
@RamyAlshurafa @amusameh @dupreesi - I think we need to split this out into smaller issues as there is A LOT in here! 

Initial thoughts as to how this can be broken down:
- Updating the review look and functionality (e.g. putting the stars next to the user) 
- Create the tabs and two different views between overview and detailed
- Overall final design changes (to be done after the top two are completed) 
- Level 1 profile view (to be done after the top two are completed) 

What do people think?

**Comment by thejoefriel** [comment]
@theharrisonmoore - do you have the updated wireframes for this? It seems that there are a number of new wireframes again. To avoid confusion, I'd suggest:
- We close issue #741 
- We create new Figma project with the new wireframes relevant for this chunk 
- We create a new issue similar to #741 which outlines the wireframes to follow for the team on this next chunk of work 

Let me know your thoughts

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> I anticipated this and have
already added the new issues to 741 (so don't delete it). I also
deleted the old wireframe URLs ready for the new ones. The only reason I
didn't attach the new wireframes was because I couldn't remember what
format you need them in and wanted to ask you…

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore  I think it's best to have it as a new issue please if that's ok? 

Changing a pre-existing link to wireframes means we lose a proper log of what the wireframes were when and for which issues, and makes it harder for me to check back to see what is missed etc.

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> That makes sense. Yeah, create a
brand new issue for these new wireframes.

Shit! I foolishly deleted the list of issues from 741 and replaced them
with the latest ones. Sorry, I won't do that again.

**Comment by thejoefriel** [comment]
No worries! Thanks @theharrisonmoore will create the issue now. Please let me know if the issues I include are correct

**Comment by thejoefriel** [comment]
This issue now has been split into #805 #806 #807 and #808
