### ISSUE TITLE
Design changes

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#899]
We need to make the following design changes:

We need to change the word 'username' to 'display name' in the following places:

- [x] Thank you page
<img width="395" alt="Screenshot 2019-12-21 at 16 58 15" src="https://user-images.githubusercontent.com/45825100/71311028-3fb49800-2413-11ea-85f1-e11f88d5e786.png">

- [x] Editing profile
<img width="334" alt="Screenshot 2019-12-21 at 17 02 42" src="https://user-images.githubusercontent.com/45825100/71311066-bc477680-2413-11ea-94c0-6b1673b8a573.png">

- [x] Changing display name
<img width="333" alt="Screenshot 2019-12-21 at 17 03 19" src="https://user-images.githubusercontent.com/45825100/71311073-dc773580-2413-11ea-9412-7887587eeb02.png">

- [x] FAQ and how to use earwig page (in four places)

We need to change the words 'main contractor' to 'main company' in the following places:

- [x] Worksite reviewing page
<img width="456" alt="Screenshot 2019-12-21 at 17 08 59" src="https://user-images.githubusercontent.com/45825100/71311126-9f5f7300-2414-11ea-89c9-65c4f703a651.png">

- [x] Worksite profile page
<img width="616" alt="Screenshot 2019-12-22 at 08 01 22" src="https://user-images.githubusercontent.com/45825100/71319093-48e44a00-2491-11ea-8c0c-0a47bacd508c.png">

- [x] Ensure it's updated in the backend database for export.

- [x] Add icons to profile page counters (see folder: https://drive.google.com/drive/folders/1rtzCm0edRuuJSHWSuHiGWBlohnPEQUGJ)
<img width="448" alt="Screenshot 2019-12-22 at 09 22 58" src="https://user-images.githubusercontent.com/45825100/71319952-c5c8f100-249c-11ea-85b1-10866d6c2e87.png">

- [x] Update text on points page
<img width="348" alt="Screenshot 2019-12-22 at 09 37 03" src="https://user-images.githubusercontent.com/45825100/71320101-a7fc8b80-249e-11ea-84f3-ae85d96f6800.png">

- [x] Add icon to competition popup
<img width="277" alt="Screenshot 2019-12-22 at 09 37 43" src="https://user-images.githubusercontent.com/45825100/71320107-bcd91f00-249e-11ea-9d35-a675219b484d.png">

- [x] Add entity logo placeholders in front of entity names in lists
<img width="330" alt="Screenshot 2019-12-22 at 08 49 58" src="https://user-images.githubusercontent.com/45825100/71319583-37527080-2498-11ea-9e4c-43ad1cde2ae5.png">

- [x] While agencies, payrolls and companies have logo placeholders, worksites should have their own logo icon (see folder: https://drive.google.com/drive/folders/1rtzCm0edRuuJSHWSuHiGWBlohnPEQUGJ)
<img width="494" alt="Screenshot 2019-12-22 at 08 54 43" src="https://user-images.githubusercontent.com/45825100/71319634-c65f8880-2498-11ea-8b42-f1831f9b29bd.png">

- [x] Ensure these logos and logo placeholders also appear on entity profile pages in the coloured header bar
<img width="802" alt="Screenshot 2019-12-22 at 08 57 05" src="https://user-images.githubusercontent.com/45825100/71319660-1b030380-2499-11ea-96ad-c21b24bedccf.png">

- [x] This text should instead say 'No recent reviews yet'
![IMG_0295](https://user-images.githubusercontent.com/45825100/70797905-72b8b500-1d9d-11ea-85a3-7e18815dd895.jpg)

- [x] This text should instead say 'Your reply will be shown publicly as soon as we've checked your verification photo.'
![IMG_0296](https://user-images.githubusercontent.com/45825100/70798090-f2df1a80-1d9d-11ea-9068-aa7d6dfe789a.jpg)

- [x] This text should instead say 'No need! We're currently checking your photo. Give us a few minutes'
![IMG_0297](https://user-images.githubusercontent.com/45825100/70798570-2ff7dc80-1d9f-11ea-8acb-d174f602cdbb.jpg)

- [x] This icon should be updated to the new Report icon
![IMG_EBEE804D5A12-1](https://user-images.githubusercontent.com/45825100/70860017-6c9d1280-1f1c-11ea-8b15-ab7bcd3e598c.jpeg)

- [x] Remove 'Homepage video' from FAQ and remove it from the contents list, too
- [x] Remove 'An important message for workers' video from FAQ and remove it from the contents list, too

- [x] Update every earwig logo with new SVG file (replacing the Beta logo) (see folder: https://drive.google.com/drive/folders/1rtzCm0edRuuJSHWSuHiGWBlohnPEQUGJ)
- [x] On sign up and login pages, ensure logo hyperlinks to Welcome page
<img width="342" alt="Screenshot 2019-12-22 at 08 05 04" src="https://user-images.githubusercontent.com/45825100/71319126-fa837b00-2491-11ea-96d8-332f0ef853a7.png">

- [x] Ensure logo is updated on all pages, and all emails that are sent to users.

- [x] Update the text on the Welcome page to say this. Make the font size 15pt, bold. Pay close attention to the 'and' that is italicised:
<img width="363" alt="Screenshot 2019-12-15 at 15 44 58" src="https://user-images.githubusercontent.com/45825100/70864427-04692380-1f52-11ea-8032-0d349d0bedbd.png">

- [x] Add icons to each question when giving reviews (see folder: https://drive.google.com/drive/folders/1rtzCm0edRuuJSHWSuHiGWBlohnPEQUGJ)
<img width="359" alt="Screenshot 2019-12-15 at 17 36 15" src="https://user-images.githubusercontent.com/45825100/70865759-709f5380-1f61-11ea-83ec-c08cfb918e6c.png">

- [x] Add icons to each question on entity profiles, too.
<img width="351" alt="Screenshot 2019-12-15 at 17 36 51" src="https://user-images.githubusercontent.com/45825100/70865764-8280f680-1f61-11ea-88ff-135a221b5a29.png">

- [x] Ensure each icon is sized so it could fit inside a square that is 45px x 45px.
<img width="777" alt="Screenshot 2019-12-15 at 17 37 36" src="https://user-images.githubusercontent.com/45825100/70865778-a80e0000-1f61-11ea-8a30-f118b79c0e05.png">

- [x] Ensure correct spacings throughout designs
<img width="801" alt="Screenshot 2019-12-22 at 07 33 37" src="https://user-images.githubusercontent.com/45825100/71318816-f9504f00-248d-11ea-80e3-f01c18667faf.png">

- [x] Make the menu icon and the home icon in the header bar blue (please use the same blue as the buttons)
<img width="517" alt="Screenshot 2019-12-16 at 09 46 36" src="https://user-images.githubusercontent.com/45825100/70892271-1ba72000-1fe9-11ea-9c4b-a1682d01de05.png">

- [x] Indent replies 28px
<img width="531" alt="Screenshot 2019-12-22 at 07 57 30" src="https://user-images.githubusercontent.com/45825100/71319062-dbd0b480-2490-11ea-8158-8618f4c464ab.png">

- [x] Fix 'Review this entity' to tabs when scrolling
<img width="410" alt="Screenshot 2019-12-17 at 09 08 00" src="https://user-images.githubusercontent.com/45825100/70976762-cfbdaf00-20ac-11ea-8b38-5c150f3d4a8b.png">

- [x] Add icon to verification popup
<img width="444" alt="Screenshot 2019-12-17 at 09 34 04" src="https://user-images.githubusercontent.com/45825100/70978670-7fe0e700-20b0-11ea-8add-778e171941b5.png">

- [x] Add icon to all pre-reviewing pages and centre justify text.
<img width="328" alt="Screenshot 2019-12-18 at 14 51 15" src="https://user-images.githubusercontent.com/45825100/71096263-e4ca3900-21a5-11ea-9f9e-08f87a4fbcc6.png">

- [x] Change 4th star rating from 'Great' to 'Good'
<img width="693" alt="Screenshot 2019-12-22 at 08 10 58" src="https://user-images.githubusercontent.com/45825100/71319172-b5137d80-2492-11ea-99f2-5f1d0c40887c.png">

- [x] Render the appropriate star label on overall rating on entity profile pages
<img width="891" alt="Screenshot 2019-12-22 at 08 15 42" src="https://user-images.githubusercontent.com/45825100/71319232-58649280-2493-11ea-9314-c888eccbf60d.png">

**Updates to all fonts and icons**
We need to make the following updates to fonts across the entire app. These are in line with the latest Web Content Accessibility Guidelines (WCAG). I will try to be as detailed as I can and I've included screenshots from the wireframes to illustrate, but if you are not sure, please just ask me and I'll tell you right away.

- [x] Make _all_ fonts Arial
- [x] On Welcome page, make 'Welcome' 50pt, **bold**.
- [x] Make all other main headings 18pt, **bold**, HEX#949494
<img width="332" alt="Screenshot 2019-12-18 at 14 56 54" src="https://user-images.githubusercontent.com/45825100/71096684-a97c3a00-21a6-11ea-8360-296fde694e9f.png">
<img width="407" alt="Screenshot 2019-12-18 at 14 57 33" src="https://user-images.githubusercontent.com/45825100/71096745-c1ec5480-21a6-11ea-9df7-227773cfe597.png">

- [x] Make all button labels 15pt, **bold** (don't change the size of the buttons)
<img width="400" alt="Screenshot 2019-12-18 at 14 58 43" src="https://user-images.githubusercontent.com/45825100/71096848-f4964d00-21a6-11ea-946d-306e61f0b4d3.png">
<img width="411" alt="Screenshot 2019-12-18 at 15 02 07" src="https://user-images.githubusercontent.com/45825100/71097121-65d60000-21a7-11ea-81fb-f33eb9612bde.png">

- [x] Make all other subheadings 15pt, **bold**, HEX#767676
<img width="429" alt="Screenshot 2019-12-18 at 15 04 17" src="https://user-images.githubusercontent.com/45825100/71097307-b5b4c700-21a7-11ea-91e9-9ecaf8cccafa.png">
<img width="337" alt="Screenshot 2019-12-18 at 15 03 52" src="https://user-images.githubusercontent.com/45825100/71097308-b64d5d80-21a7-11ea-886a-8b1266004d55.png">
<img width="318" alt="Screenshot 2019-12-18 at 15 03 21" src="https://user-images.githubusercontent.com/45825100/71097309-b64d5d80-21a7-11ea-8ec2-f8752130c2c6.png">

- [x] Make all other body text 15pt, regular, HEX#767676
<img width="324" alt="Screenshot 2019-12-18 at 15 07 22" src="https://user-images.githubusercontent.com/45825100/71097616-222fc600-21a8-11ea-985b-092325926bb9.png">
<img width="330" alt="Screenshot 2019-12-18 at 15 07 04" src="https://user-images.githubusercontent.com/45825100/71097618-22c85c80-21a8-11ea-9429-a04d7320e250.png">
<img width="354" alt="Screenshot 2019-12-18 at 15 06 20" src="https://user-images.githubusercontent.com/45825100/71097620-22c85c80-21a8-11ea-8ea6-31a640f06d4e.png">

**Special cases**
There are some special cases where fonts need to be irregular sizes:

**Display names and points**
- [x] Make display names and points 12pt, HEX#767676
- [x] Make the display name itself **bold**
- [x] Make the trade regular, _italics_
- [x] Make the points regular
- [x] Make the verification icon beside it 12pt x 12pt square
- [x] Ensure this is how the display name and points are displayed across every page where they are shown
<img width="622" alt="Screenshot 2019-12-18 at 15 13 39" src="https://user-images.githubusercontent.com/45825100/71098068-ffea7800-21a8-11ea-8590-c6de0dc46122.png">

**Icons**
- [x] Make all icons HEX#949494
<img width="446" alt="Screenshot 2019-12-18 at 15 15 25" src="https://user-images.githubusercontent.com/45825100/71098205-40e28c80-21a9-11ea-9d53-868d7b5118bf.png">
<img width="330" alt="Screenshot 2019-12-18 at 15 15 12" src="https://user-images.githubusercontent.com/45825100/71098206-40e28c80-21a9-11ea-9758-22ad412154d6.png">
<img width="328" alt="Screenshot 2019-12-18 at 15 14 58" src="https://user-images.githubusercontent.com/45825100/71098207-40e28c80-21a9-11ea-97b1-7f2c611f4006.png">

**Additional**
- [x] Make voice review alert text **bold**, _italics_
<img width="529" alt="Screenshot 2019-12-18 at 15 17 11" src="https://user-images.githubusercontent.com/45825100/71098356-7dae8380-21a9-11ea-99f0-2ce77cb82d16.png">
